### ISSUE TITLE
New feature: be able to get a single tile

### ISSUE THREAD

**Issue by mverburg** [imintel/mbtiles4j#2]
When using the `MBTilesReader` only provides a method to get a Tile iterator. Sometimes it can be useful to be able to retrieve a single tile. 

This is at least something I need for my project. That is why I'd like to propose a new method for the `MBTilesReader`. It's signature would look something like: ` public Tile getTile(int z, int x, int y);`

I'll offer a pull request when I've implement this.

**Comment by mverburg** [comment]
I've started implementing the new method. In order to do so I've factored out `Tile` to be a top level class. @Ccook is there any objection of me doing so?

**Comment by ghost** [comment]
No objection, and thank you for pointing out that oversight. I've accepted the pull request, version bumped to 1.0.6, and synced it with Maven Central.  Below are the pom coordinates.

```
<dependency>
  <groupId>org.imintel</groupId>
  <artifactId>mbtiles4j</artifactId>
  <version>1.0.6</version>
</dependency>
```

Thanks again, @mverburg
